git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: true
gui:
  language: 'en'
  sidePanelWidth: 0.15
  showIcons: true
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
refresher:
  refreshInterval: 3
os:
  editCommand: "nvim"

