theme = "Midnight"
mode = "auto"
vcs = "git"
watch = true 
exclude_untracked = false
line_numbers = true
tab_width = 4
wrap_lines = true 
menu_bar = true
agent_notes = false
prompt_save_view_preferences = true
transparent_background = true 
