#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config external_bar off:40:0
yabai -m config menubar_opacity 1.0
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config display_arrangement_order default

yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_insertion_point focused
yabai -m config window_zoom_persist on
yabai -m config window_shadow on
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_easing ease_out_circ
yabai -m config window_opacity_duration 0.0

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90

yabai -m config window_opacity off

yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 06
yabai -m config layout bsp

yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Debug enabled
yabai -m config debug_output on

# Rules
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Raycast Settings$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Postlab$" manage=off
yabai -m rule --add app="^Simulator$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^システム設定$" manage=off
yabai -m rule --add app="^LINE$" manage=off
yabai -m rule --add app="^Electron$" manage=off

echo "yabai configuration loaded.."
